/*
 * Gotify REST-API.
 * This is the documentation of the Gotify REST-API.  # Authentication In Gotify there are two token types: __clientToken__: a client is something that receives message and manages stuff like creating new tokens or delete messages. (f.ex this token should be used for an android app) __appToken__: an application is something that sends messages (f.ex. this token should be used for a shell script)  The token can be transmitted in a header named `X-Gotify-Key`, in a query parameter named `token` or through a header named `Authorization` with the value prefixed with `Bearer` (Ex. `Bearer randomtoken`). There is also the possibility to authenticate through basic auth, this should only be used for creating a clientToken.  \\---  Found a bug or have some questions? [Create an issue on GitHub](https://github.com/gotify/server/issues)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.gotify.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * The Application holds information about an app which can send notifications.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class Application {
  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_DEFAULT_PRIORITY = "defaultPriority";
  @SerializedName(SERIALIZED_NAME_DEFAULT_PRIORITY)
  @javax.annotation.Nullable
  private Long defaultPriority;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nonnull
  private String description;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private Long id;

  public static final String SERIALIZED_NAME_IMAGE = "image";
  @SerializedName(SERIALIZED_NAME_IMAGE)
  @javax.annotation.Nonnull
  private String image;

  public static final String SERIALIZED_NAME_INTERNAL = "internal";
  @SerializedName(SERIALIZED_NAME_INTERNAL)
  @javax.annotation.Nonnull
  private Boolean internal;

  public static final String SERIALIZED_NAME_LAST_USED = "lastUsed";
  @SerializedName(SERIALIZED_NAME_LAST_USED)
  @javax.annotation.Nullable
  private OffsetDateTime lastUsed;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_SORT_KEY = "sortKey";
  @SerializedName(SERIALIZED_NAME_SORT_KEY)
  @javax.annotation.Nonnull
  private String sortKey;

  public static final String SERIALIZED_NAME_TOKEN = "token";
  @SerializedName(SERIALIZED_NAME_TOKEN)
  @javax.annotation.Nullable
  private String token;

  public Application() {
  }
  /**
   * Constructor with only readonly parameters
   */
  
  public Application(
     OffsetDateTime createdAt, 
     Long id, 
     String image, 
     Boolean internal, 
     OffsetDateTime lastUsed, 
     String token
  ) {
    this();
    this.createdAt = createdAt;
    this.id = id;
    this.image = image;
    this.internal = internal;
    this.lastUsed = lastUsed;
    this.token = token;
  }

  /**
   * The date the application was created.
   * @return createdAt
   */
  @javax.annotation.Nonnull

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }



  public Application defaultPriority(@javax.annotation.Nullable Long defaultPriority) {
    
    this.defaultPriority = defaultPriority;
    return this;
  }

  /**
   * The default priority of messages sent by this application. Defaults to 0.
   * @return defaultPriority
   */
  @javax.annotation.Nullable

  public Long getDefaultPriority() {
    return defaultPriority;
  }


  public void setDefaultPriority(@javax.annotation.Nullable Long defaultPriority) {
    this.defaultPriority = defaultPriority;
  }

  public Application description(@javax.annotation.Nonnull String description) {
    
    this.description = description;
    return this;
  }

  /**
   * The description of the application.
   * @return description
   */
  @javax.annotation.Nonnull

  public String getDescription() {
    return description;
  }


  public void setDescription(@javax.annotation.Nonnull String description) {
    this.description = description;
  }

  /**
   * The application id.
   * @return id
   */
  @javax.annotation.Nonnull

  public Long getId() {
    return id;
  }



  /**
   * The image of the application.
   * @return image
   */
  @javax.annotation.Nonnull

  public String getImage() {
    return image;
  }



  /**
   * Whether the application is an internal application. Internal applications should not be deleted.
   * @return internal
   */
  @javax.annotation.Nonnull

  public Boolean getInternal() {
    return internal;
  }



  /**
   * The last time the application token was used.
   * @return lastUsed
   */
  @javax.annotation.Nullable

  public OffsetDateTime getLastUsed() {
    return lastUsed;
  }



  public Application name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The application name. This is how the application should be displayed to the user.
   * @return name
   */
  @javax.annotation.Nonnull

  public String getName() {
    return name;
  }


  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public Application sortKey(@javax.annotation.Nonnull String sortKey) {
    
    this.sortKey = sortKey;
    return this;
  }

  /**
   * The sort key of this application. Uses fractional indexing.
   * @return sortKey
   */
  @javax.annotation.Nonnull

  public String getSortKey() {
    return sortKey;
  }


  public void setSortKey(@javax.annotation.Nonnull String sortKey) {
    this.sortKey = sortKey;
  }

  /**
   * The application token. Can be used as &#x60;appToken&#x60;. See Authentication.
   * @return token
   */
  @javax.annotation.Nullable

  public String getToken() {
    return token;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Application application = (Application) o;
    return Objects.equals(this.createdAt, application.createdAt) &&
        Objects.equals(this.defaultPriority, application.defaultPriority) &&
        Objects.equals(this.description, application.description) &&
        Objects.equals(this.id, application.id) &&
        Objects.equals(this.image, application.image) &&
        Objects.equals(this.internal, application.internal) &&
        Objects.equals(this.lastUsed, application.lastUsed) &&
        Objects.equals(this.name, application.name) &&
        Objects.equals(this.sortKey, application.sortKey) &&
        Objects.equals(this.token, application.token);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, defaultPriority, description, id, image, internal, lastUsed, name, sortKey, token);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Application {\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    defaultPriority: ").append(toIndentedString(defaultPriority)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    internal: ").append(toIndentedString(internal)).append("\n");
    sb.append("    lastUsed: ").append(toIndentedString(lastUsed)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    sortKey: ").append(toIndentedString(sortKey)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

