/*
 * Gotify REST-API.
 * This is the documentation of the Gotify REST-API.  # Authentication In Gotify there are two token types: __clientToken__: a client is something that receives message and manages stuff like creating new tokens or delete messages. (f.ex this token should be used for an android app) __appToken__: an application is something that sends messages (f.ex. this token should be used for a shell script)  The token can be transmitted in a header named `X-Gotify-Key`, in a query parameter named `token` or through a header named `Authorization` with the value prefixed with `Bearer` (Ex. `Bearer randomtoken`). There is also the possibility to authenticate through basic auth, this should only be used for creating a clientToken.  \\---  Found a bug or have some questions? [Create an issue on GitHub](https://github.com/gotify/server/issues)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.gotify.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * The Client holds information about a device which can receive notifications (and other stuff).
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class Client {
  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_ELEVATED_UNTIL = "elevatedUntil";
  @SerializedName(SERIALIZED_NAME_ELEVATED_UNTIL)
  @javax.annotation.Nullable
  private OffsetDateTime elevatedUntil;

  public static final String SERIALIZED_NAME_EXPIRES_AFTER_INACTIVITY_SECONDS = "expiresAfterInactivitySeconds";
  @SerializedName(SERIALIZED_NAME_EXPIRES_AFTER_INACTIVITY_SECONDS)
  @javax.annotation.Nullable
  private Long expiresAfterInactivitySeconds;

  public static final String SERIALIZED_NAME_EXPIRES_AT = "expiresAt";
  @SerializedName(SERIALIZED_NAME_EXPIRES_AT)
  @javax.annotation.Nullable
  private OffsetDateTime expiresAt;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private Long id;

  public static final String SERIALIZED_NAME_LAST_USED = "lastUsed";
  @SerializedName(SERIALIZED_NAME_LAST_USED)
  @javax.annotation.Nullable
  private OffsetDateTime lastUsed;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_TOKEN = "token";
  @SerializedName(SERIALIZED_NAME_TOKEN)
  @javax.annotation.Nullable
  private String token;

  public Client() {
  }
  /**
   * Constructor with only readonly parameters
   */
  
  public Client(
     OffsetDateTime createdAt, 
     OffsetDateTime elevatedUntil, 
     OffsetDateTime expiresAt, 
     Long id, 
     OffsetDateTime lastUsed, 
     String token
  ) {
    this();
    this.createdAt = createdAt;
    this.elevatedUntil = elevatedUntil;
    this.expiresAt = expiresAt;
    this.id = id;
    this.lastUsed = lastUsed;
    this.token = token;
  }

  /**
   * The date the client was created.
   * @return createdAt
   */
  @javax.annotation.Nonnull

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }



  /**
   * The time until which this client&#39;s session is elevated.
   * @return elevatedUntil
   */
  @javax.annotation.Nullable

  public OffsetDateTime getElevatedUntil() {
    return elevatedUntil;
  }



  public Client expiresAfterInactivitySeconds(@javax.annotation.Nullable Long expiresAfterInactivitySeconds) {
    
    this.expiresAfterInactivitySeconds = expiresAfterInactivitySeconds;
    return this;
  }

  /**
   * The number of seconds of inactivity after which the client is removed. 0 means the client never expires.
   * @return expiresAfterInactivitySeconds
   */
  @javax.annotation.Nullable

  public Long getExpiresAfterInactivitySeconds() {
    return expiresAfterInactivitySeconds;
  }


  public void setExpiresAfterInactivitySeconds(@javax.annotation.Nullable Long expiresAfterInactivitySeconds) {
    this.expiresAfterInactivitySeconds = expiresAfterInactivitySeconds;
  }

  /**
   * The time at which this client will expire due to inactivity, or null if it never expires.
   * @return expiresAt
   */
  @javax.annotation.Nullable

  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }



  /**
   * The client id.
   * @return id
   */
  @javax.annotation.Nonnull

  public Long getId() {
    return id;
  }



  /**
   * The last time the client token was used.
   * @return lastUsed
   */
  @javax.annotation.Nullable

  public OffsetDateTime getLastUsed() {
    return lastUsed;
  }



  public Client name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The client name. This is how the client should be displayed to the user.
   * @return name
   */
  @javax.annotation.Nonnull

  public String getName() {
    return name;
  }


  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  /**
   * The client token. Can be used as &#x60;clientToken&#x60;. See Authentication.
   * @return token
   */
  @javax.annotation.Nullable

  public String getToken() {
    return token;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Client client = (Client) o;
    return Objects.equals(this.createdAt, client.createdAt) &&
        Objects.equals(this.elevatedUntil, client.elevatedUntil) &&
        Objects.equals(this.expiresAfterInactivitySeconds, client.expiresAfterInactivitySeconds) &&
        Objects.equals(this.expiresAt, client.expiresAt) &&
        Objects.equals(this.id, client.id) &&
        Objects.equals(this.lastUsed, client.lastUsed) &&
        Objects.equals(this.name, client.name) &&
        Objects.equals(this.token, client.token);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, elevatedUntil, expiresAfterInactivitySeconds, expiresAt, id, lastUsed, name, token);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Client {\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    elevatedUntil: ").append(toIndentedString(elevatedUntil)).append("\n");
    sb.append("    expiresAfterInactivitySeconds: ").append(toIndentedString(expiresAfterInactivitySeconds)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastUsed: ").append(toIndentedString(lastUsed)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

