/*
 * Gotify REST-API.
 * This is the documentation of the Gotify REST-API.  # Authentication In Gotify there are two token types: __clientToken__: a client is something that receives message and manages stuff like creating new tokens or delete messages. (f.ex this token should be used for an android app) __appToken__: an application is something that sends messages (f.ex. this token should be used for a shell script)  The token can be transmitted in a header named `X-Gotify-Key`, in a query parameter named `token` or through a header named `Authorization` with the value prefixed with `Bearer` (Ex. `Bearer randomtoken`). There is also the possibility to authenticate through basic auth, this should only be used for creating a clientToken.  \\---  Found a bug or have some questions? [Create an issue on GitHub](https://github.com/gotify/server/issues)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.gotify.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * CurrentUserExternal Model
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class CurrentUser {
  public static final String SERIALIZED_NAME_ADMIN = "admin";
  @SerializedName(SERIALIZED_NAME_ADMIN)
  @javax.annotation.Nonnull
  private Boolean admin;

  public static final String SERIALIZED_NAME_CLIENT_ID = "clientId";
  @SerializedName(SERIALIZED_NAME_CLIENT_ID)
  @javax.annotation.Nullable
  private Long clientId;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_ELEVATED_UNTIL = "elevatedUntil";
  @SerializedName(SERIALIZED_NAME_ELEVATED_UNTIL)
  @javax.annotation.Nullable
  private OffsetDateTime elevatedUntil;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private Long id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public CurrentUser() {
  }
  /**
   * Constructor with only readonly parameters
   */
  
  public CurrentUser(
     Long clientId, 
     OffsetDateTime createdAt, 
     OffsetDateTime elevatedUntil, 
     Long id
  ) {
    this();
    this.clientId = clientId;
    this.createdAt = createdAt;
    this.elevatedUntil = elevatedUntil;
    this.id = id;
  }

  public CurrentUser admin(@javax.annotation.Nonnull Boolean admin) {
    
    this.admin = admin;
    return this;
  }

  /**
   * If the user is an administrator.
   * @return admin
   */
  @javax.annotation.Nonnull

  public Boolean getAdmin() {
    return admin;
  }


  public void setAdmin(@javax.annotation.Nonnull Boolean admin) {
    this.admin = admin;
  }

  /**
   * The client id of the current session.
   * @return clientId
   */
  @javax.annotation.Nullable

  public Long getClientId() {
    return clientId;
  }



  /**
   * The date the user was created.
   * @return createdAt
   */
  @javax.annotation.Nonnull

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }



  /**
   * The time until which the session is elevated.
   * @return elevatedUntil
   */
  @javax.annotation.Nullable

  public OffsetDateTime getElevatedUntil() {
    return elevatedUntil;
  }



  /**
   * The user id.
   * @return id
   */
  @javax.annotation.Nonnull

  public Long getId() {
    return id;
  }



  public CurrentUser name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The user name. For login.
   * @return name
   */
  @javax.annotation.Nonnull

  public String getName() {
    return name;
  }


  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CurrentUser currentUser = (CurrentUser) o;
    return Objects.equals(this.admin, currentUser.admin) &&
        Objects.equals(this.clientId, currentUser.clientId) &&
        Objects.equals(this.createdAt, currentUser.createdAt) &&
        Objects.equals(this.elevatedUntil, currentUser.elevatedUntil) &&
        Objects.equals(this.id, currentUser.id) &&
        Objects.equals(this.name, currentUser.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(admin, clientId, createdAt, elevatedUntil, id, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CurrentUser {\n");
    sb.append("    admin: ").append(toIndentedString(admin)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    elevatedUntil: ").append(toIndentedString(elevatedUntil)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

