/*
 * Gotify REST-API.
 * This is the documentation of the Gotify REST-API.  # Authentication In Gotify there are two token types: __clientToken__: a client is something that receives message and manages stuff like creating new tokens or delete messages. (f.ex this token should be used for an android app) __appToken__: an application is something that sends messages (f.ex. this token should be used for a shell script)  The token can be transmitted in a header named `X-Gotify-Key`, in a query parameter named `token` or through a header named `Authorization` with the value prefixed with `Bearer` (Ex. `Bearer randomtoken`). There is also the possibility to authenticate through basic auth, this should only be used for creating a clientToken.  \\---  Found a bug or have some questions? [Create an issue on GitHub](https://github.com/gotify/server/issues)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.gotify.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * The SecurityUpdateAction describes the details of a requested security update.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class SecurityUpdateAction {
  public static final String SERIALIZED_NAME_REGENERATE_TOKEN = "regenerateToken";
  @SerializedName(SERIALIZED_NAME_REGENERATE_TOKEN)
  @javax.annotation.Nullable
  private Boolean regenerateToken;

  public SecurityUpdateAction() {
  }

  public SecurityUpdateAction regenerateToken(@javax.annotation.Nullable Boolean regenerateToken) {
    
    this.regenerateToken = regenerateToken;
    return this;
  }

  /**
   * Whether to regenerate the token. Your client token must be elevated to perform this action.
   * @return regenerateToken
   */
  @javax.annotation.Nullable

  public Boolean getRegenerateToken() {
    return regenerateToken;
  }


  public void setRegenerateToken(@javax.annotation.Nullable Boolean regenerateToken) {
    this.regenerateToken = regenerateToken;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecurityUpdateAction securityUpdateAction = (SecurityUpdateAction) o;
    return Objects.equals(this.regenerateToken, securityUpdateAction.regenerateToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(regenerateToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecurityUpdateAction {\n");
    sb.append("    regenerateToken: ").append(toIndentedString(regenerateToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

